name: Build SpikeGLX

on:
    workflow_dispatch:
    workflow_call:
    push:
      branches:
        - master

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: windows-2022
                      arch: x64
                      base_name: windows-x86_64
                    - os: macos-15
                      arch: arm64
                      base_name: mac-arm64
                    - os: macos-15
                      arch: x64
                      base_name: mac-x86_64

        runs-on: ${{ matrix.os }}

        steps:
            - name: Install build system
              run: pipx install conan ninja

            - name: Setup Compiler (Windows)
              uses: ilammy/msvc-dev-cmd@138b1c783b65ec697d8342918306b7b2db4e88f1
              if: matrix.os == 'windows-2022'

            - name: Setup Compiler (MacOS)
              if: matrix.os == 'macos-15'
              run: |
                  echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV
                  echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV

            - name: Install Qt
              uses: jurplel/install-qt-action@v4
              with:
                version: '6.10.*'
                cache: true

            - name: Checkout code
              uses: actions/checkout@v6

            - name: conan cache
              id: conan_cache
              uses: actions/cache@v5
              with:
                  path: ~/.conan2
                  key: conan-${{ matrix.os }}-${{ matrix.arch }}

            - name: Clone submodules and setup Conan
              run: |
                  conan config install .github/conan_profiles/${{ matrix.os }}-${{ matrix.arch }} -tf profiles
                  git clone https://github.com/kontex-neuro/kontex-conan.git kontex-conan
                  conan remote add --force kontex-neuro ./kontex-conan

            - name: Build SpikeGLX
              run: |
                  conan install . --build=missing --profile:all ${{ matrix.os }}-${{ matrix.arch }} -s build_type=Release
                  cmake -S . -B build/Release --preset conan-release -DCMAKE_INSTALL_PREFIX=install
                  cmake --build build/Release --preset conan-release --target install

            - name: Package SpikeGLX (Windows)
              if: matrix.base_name == 'windows-x86_64'
              run: |
                  cmake --build build/Release --preset conan-release --target package
                  cp build/Release/package/SpikeGLX-*-win64.exe install/

            - name: Package SpikeGLX (macOS)
              if: matrix.os == 'macos-15'
              env:
                  CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
                  CERTIFICATE_PWD: ${{ secrets.CERTIFICATE_PWD }}
                  KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD }}
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  TEAM_ID: ${{ secrets.TEAM_ID }}
                  APP_PWD: ${{ secrets.APP_PWD }}
              run: |
                  echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
                  security create-keychain -p $KEYCHAIN_PWD build.keychain
                  security default-keychain -s build.keychain
                  security unlock-keychain -p $KEYCHAIN_PWD build.keychain
                  security import certificate.p12 -k build.keychain -P $CERTIFICATE_PWD -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PWD build.keychain

                  # Build package and sign
                  cmake --build build/Release --preset conan-release --target package

                  # Notarize
                  xcrun notarytool store-credentials "kontex" --apple-id "$APPLE_ID" --team-id "$TEAM_ID" --password "$APP_PWD"
                  find build/Release/package \
                    -name 'SpikeGLX-*-Darwin.dmg' \
                    -exec xcrun notarytool submit {} --keychain-profile "kontex" --wait \; \
                    -exec xcrun stapler staple {} \;
                  cp build/Release/package/SpikeGLX-*-Darwin.dmg install/
            
            - name: zip
              shell: bash
              run: |
                  7z a ${{ matrix.base_name }}.zip ./install/*

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: ${{ matrix.base_name }}
                  path: ${{ matrix.base_name }}.zip

    build-linux:
        runs-on: ubuntu-22.04
        container: ghcr.io/kontex-neuro/ubuntu22-gcc13:latest
        env:
            OS_NAME: ubuntu-22.04
            ARCH_NAME: x64
            BASE_NAME: linux-x86_64

        steps:
            - name: Install extra dependencies
              run: |
                  apt-get update -y
                  apt-get install -y libasound2-dev mesa-common-dev libglu1-mesa-dev
                  rm -rf /var/lib/apt/lists/*

            - name: Conan cache
              uses: actions/cache@v5
              with:
                  path: ~/.conan2
                  key: conan-ubuntu-22.04-x64

            - name: Install Qt
              uses: jurplel/install-qt-action@v4
              with:
                version: '6.11.*'
                cache: true

            - name: Checkout code
              uses: actions/checkout@v6

            - name: Clone submodules and setup Conan
              shell: bash
              run: |
                  conan config install .github/conan_profiles/${{ env.OS_NAME }}-${{ env.ARCH_NAME }} -tf profiles
                  git clone https://github.com/kontex-neuro/kontex-conan.git kontex-conan
                  conan remote add --force kontex-neuro ./kontex-conan

            - name: Build SpikeGLX
              shell: bash
              run: |
                  conan install . --build=missing --profile:all ${{ env.OS_NAME }}-${{ env.ARCH_NAME }} -s build_type=Release
                  cmake -S . -B build/Release --preset conan-release -DCMAKE_INSTALL_PREFIX=install
                  cmake --build build/Release --preset conan-release --target install

            - name: zip
              shell: bash
              run: |
                  7z a ${{ env.BASE_NAME }}.zip ./install/*

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: ${{ env.BASE_NAME }}
                  path: ${{ env.BASE_NAME }}.zip
